# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MeesageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):
        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(536, 169)
        self.gridLayout = QtWidgets.QGridLayout(MessageDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Ok_button = QtWidgets.QPushButton(MessageDialog)
        self.Ok_button.setObjectName("Ok_button")
        self.gridLayout.addWidget(self.Ok_button, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(MessageDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)

        self.retranslateUi(MessageDialog)
        QtCore.QMetaObject.connectSlotsByName(MessageDialog)

    def retranslateUi(self, MessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", "Message Dialog"))
        self.Ok_button.setText(_translate("MessageDialog", "OK"))
        self.label.setText(_translate("MessageDialog", "Message:"))
