# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RequiredFieldsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FieldsRequiredDialog(object):
    def setupUi(self, FieldsRequiredDialog):
        FieldsRequiredDialog.setObjectName("FieldsRequiredDialog")
        FieldsRequiredDialog.resize(353, 378)
        self.gridLayout = QtWidgets.QGridLayout(FieldsRequiredDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FieldsRequiredDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.errorList = QtWidgets.QListView(FieldsRequiredDialog)
        self.errorList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.errorList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.errorList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.errorList.setAlternatingRowColors(False)
        self.errorList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.errorList.setObjectName("errorList")
        self.gridLayout.addWidget(self.errorList, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(251, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(FieldsRequiredDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)

        self.retranslateUi(FieldsRequiredDialog)
        QtCore.QMetaObject.connectSlotsByName(FieldsRequiredDialog)

    def retranslateUi(self, FieldsRequiredDialog):
        _translate = QtCore.QCoreApplication.translate
        FieldsRequiredDialog.setWindowTitle(_translate("FieldsRequiredDialog", "Fields Required"))
        self.label.setText(_translate("FieldsRequiredDialog", "The following fields are required:"))
        self.pushButton.setText(_translate("FieldsRequiredDialog", "OK"))
