# Generated by Django 3.1.1 on 2020-09-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_auto_20200921_0836'),
        ('sales', '0002_customerorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customerorder', verbose_name='Return from order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity returner of the product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Product Returner from order')),
                ('return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.orderreturn', verbose_name='Order Line Returned')),
            ],
        ),
    ]
