"""
Django settings for apotekia project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ao%_$xyw%vgq65%nsahn(p%a+_(j2u5^f)6lbst2026z^#vk4f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# Application definition

APPS = ['address',
        'banking',
        'customers',
        'catalog',
        'inventory',
        'payment',
        'returns',
        'sales',
        'suppliers',
        ]

DEBUG_APPS = [
        'import_export',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + APPS
if DEBUG:
    INSTALLED_APPS = INSTALLED_APPS + DEBUG_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apotekia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apotekia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
IMAGE_FOLDER = os.path.join(BASE_DIR, "images")

DEFAULT_CURRENCY = 'Dh'
DEFAULT_ADDRESS_FIELDS = ('first_name', 'last_name', 'line1', 'line4', 'postcode', 'country')

# GENERAL PREFIXES
CONTACT_PREFIX = 'CO-'

# Customer document prefixes
CUSTOMER_PREFIX = 'CU-'
CUSTOMER_PROFORMA_PREFIX = 'PI-'
CUSTOMER_ORDER_PREFIX = 'CPO-'
CUSTOMER_INVOICE_PREFIX = 'FAC-'
CUSTOMER_BL_PREFIX = 'BL-'
CUSTOMER_CREDIT_NOTE_PREFIX = 'CCN-'

# SUPPLIER PREFIXES
SUPPLIER_PREFIX = 'SU-'
SUPPLIER_PROFORMA_PREFIX = 'SPI-'
SUPPLIER_ORDER_PREFIX = 'PO-'
SUPPLIER_INVOICE_PREFIX = 'S-FAC-'
SUPPLIER_BL_PREFIX = 'S-BL-'
SUPPLIER_CREDIT_NOTE_PREFIX = 'SCN-'

# FINANCIAL PREFIXES
PAYMENT_PREFIX = 'PAY-'
