# Generated by Django 3.1.1 on 2020-10-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20, verbose_name='Account Name')),
                ('type', models.CharField(choices=[('Bank Account', 'Bank Account'), ('Cash Register', 'Cash Register'), ('Safe', 'Safe')], default='Bank Account', max_length=20, verbose_name='Account type')),
                ('date_opened', models.DateField(verbose_name='Date Opened')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number')),
                ('IBAN_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='IBAN Number')),
                ('Swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Swift CODE Number')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Initial Balance')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Balance')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='BaseBankEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_reference', models.SlugField(max_length=128, verbose_name='Line Reference')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Updated')),
                ('date_of_operation', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Of Operation')),
                ('date_of_value', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Of Value')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Value')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankaccount', verbose_name='Basket')),
            ],
            options={
                'verbose_name': 'Bank Entry',
                'verbose_name_plural': 'Bank Entries',
            },
        ),
    ]
