# Generated by Django 3.1.1 on 2020-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryTable',
        ),
    ]
