# Generated by Django 3.1.1 on 2020-09-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCustomerReturnEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='inventory.inventorylocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Customer Return Order',
                'verbose_name_plural': 'Customer Return Orders',
            },
        ),
    ]
