# Generated by Django 3.1.1 on 2020-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_inventorytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date & Time'),
        ),
    ]
