# Generated by Django 3.1.1 on 2020-09-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200921_0836'),
        ('returns', '0001_initial'),
        ('inventory', '0002_inventorycustomerreturnentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycustomerreturnentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='returns.orderreturn', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='inventorycustomerreturnentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='catalog.product', verbose_name='Product'),
        ),
    ]
