# Generated by Django 3.1.1 on 2020-09-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200921_0836'),
        ('inventory', '0003_auto_20200921_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='Initial count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Inventory Raw EntriesO',
                'verbose_name_plural': 'Inventory Raw Entries',
            },
        ),
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date and time of entries')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylocation')),
            ],
            options={
                'verbose_name': 'Inventory Table Entry',
                'verbose_name_plural': 'Inventory Table Entries',
            },
        ),
        migrations.DeleteModel(
            name='InventoryCustomerPurchaseExit',
        ),
        migrations.RemoveField(
            model_name='inventorycustomerreturnentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventorycustomerreturnentry',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inventorycustomerreturnentry',
            name='product',
        ),
        migrations.DeleteModel(
            name='InventorySupplierReturnOrder',
        ),
        migrations.DeleteModel(
            name='InventoryCustomerReturnEntry',
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorytable'),
        ),
    ]
