# Generated by Django 3.1.1 on 2020-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First title')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last title')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('id_number', models.CharField(blank=True, max_length=12, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Morocco', max_length=128, verbose_name='Country')),
            ],
        ),
    ]
