# Generated by Django 3.1.1 on 2020-09-21 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Is this product publicly visible.', verbose_name='Active')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Track stock levels?')),
                ('is_discountable', models.BooleanField(default=True, help_text='This flag indicates if this product can be used in an offer or not', verbose_name='Is discountable?')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code (UPC) is an identifier for a product which is not specific to a particular  supplier. Eg an ISBN for a book.', max_length=64, null=True, unique=True, verbose_name='UPC')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Product length dimension')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Product width dimension')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Product height dimension')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Product net weight dimension')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Product gross weight dimension')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Purchase price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Selling price')),
                ('tax_rate', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tax Rate')),
            ],
            options={
                'verbose_name': 'Product class',
                'verbose_name_plural': 'Product classes',
                'ordering': ['title'],
            },
        ),
    ]
