# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomerSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerSearchWidget(object):
    def setupUi(self, CustomerSearchWidget):
        CustomerSearchWidget.setObjectName("CustomerSearchWidget")
        CustomerSearchWidget.resize(684, 443)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CustomerSearchWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CustomerGroupBox = QtWidgets.QGroupBox(CustomerSearchWidget)
        self.CustomerGroupBox.setObjectName("CustomerGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CustomerGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CustomerSearchLabel = QtWidgets.QLabel(self.CustomerGroupBox)
        self.CustomerSearchLabel.setObjectName("CustomerSearchLabel")
        self.gridLayout_4.addWidget(self.CustomerSearchLabel, 2, 0, 1, 1)
        self.CustomerViewButton = QtWidgets.QPushButton(self.CustomerGroupBox)
        self.CustomerViewButton.setMinimumSize(QtCore.QSize(0, 40))
        self.CustomerViewButton.setMaximumSize(QtCore.QSize(16777215, 65))
        self.CustomerViewButton.setObjectName("CustomerViewButton")
        self.gridLayout_4.addWidget(self.CustomerViewButton, 4, 3, 1, 1)
        self.CustomerSelectionLabel = QtWidgets.QLabel(self.CustomerGroupBox)
        self.CustomerSelectionLabel.setObjectName("CustomerSelectionLabel")
        self.gridLayout_4.addWidget(self.CustomerSelectionLabel, 4, 0, 1, 2)
        self.CustomerSelectionButton = QtWidgets.QPushButton(self.CustomerGroupBox)
        self.CustomerSelectionButton.setMinimumSize(QtCore.QSize(0, 40))
        self.CustomerSelectionButton.setMaximumSize(QtCore.QSize(16777215, 65))
        self.CustomerSelectionButton.setObjectName("CustomerSelectionButton")
        self.gridLayout_4.addWidget(self.CustomerSelectionButton, 4, 2, 1, 1)
        self.NewCustomerButton = QtWidgets.QPushButton(self.CustomerGroupBox)
        self.NewCustomerButton.setMinimumSize(QtCore.QSize(0, 40))
        self.NewCustomerButton.setMaximumSize(QtCore.QSize(16777215, 65))
        self.NewCustomerButton.setObjectName("NewCustomerButton")
        self.gridLayout_4.addWidget(self.NewCustomerButton, 4, 4, 1, 1)
        self.CustomerResultsTable = QtWidgets.QTableView(self.CustomerGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CustomerResultsTable.setFont(font)
        self.CustomerResultsTable.setAutoFillBackground(True)
        self.CustomerResultsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.CustomerResultsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CustomerResultsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CustomerResultsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CustomerResultsTable.setObjectName("CustomerResultsTable")

        self.CustomerResultsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.CustomerResultsTable.horizontalHeader().setDefaultSectionSize(125)
        self.CustomerResultsTable.horizontalHeader().setMinimumSectionSize(60)
        self.CustomerResultsTable.horizontalHeader().setStretchLastSection(True)
        self.CustomerResultsTable.verticalHeader().setCascadingSectionResizes(False)
        self.CustomerResultsTable.verticalHeader().setSortIndicatorShown(False)
        self.CustomerResultsTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.CustomerResultsTable, 3, 0, 1, 5)
        self.AnonymousCUstomerButton = QtWidgets.QPushButton(self.CustomerGroupBox)
        self.AnonymousCUstomerButton.setMinimumSize(QtCore.QSize(0, 50))
        self.AnonymousCUstomerButton.setObjectName("AnonymousCustomerButton")
        self.gridLayout_4.addWidget(self.AnonymousCUstomerButton, 1, 0, 1, 5)
        self.CustomerSearchField = QtWidgets.QLineEdit(self.CustomerGroupBox)
        self.CustomerSearchField.setObjectName("CustomerSearchField")
        self.gridLayout_4.addWidget(self.CustomerSearchField, 2, 1, 1, 4)
        self.horizontalLayout.addWidget(self.CustomerGroupBox)

        self.retranslateUi(CustomerSearchWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomerSearchWidget)

    def retranslateUi(self, CustomerSearchWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomerSearchWidget.setWindowTitle(_translate("CustomerSearchWidget", "Form"))
        self.CustomerGroupBox.setTitle(_translate("CustomerSearchWidget", "Clients"))
        self.CustomerSearchLabel.setText(_translate("CustomerSearchWidget", "Search:"))
        self.CustomerViewButton.setText(_translate("CustomerSearchWidget", "VIEW"))
        self.CustomerSelectionLabel.setText(_translate("CustomerSearchWidget", ""))
        self.CustomerSelectionButton.setText(_translate("CustomerSearchWidget", "SELECT"))
        self.NewCustomerButton.setText(_translate("CustomerSearchWidget", "NEW"))
        self.CustomerResultsTable.setSortingEnabled(True)

        __sortingEnabled = self.CustomerResultsTable.isSortingEnabled()
        self.CustomerResultsTable.setSortingEnabled(False)

        self.CustomerResultsTable.setSortingEnabled(__sortingEnabled)
        self.AnonymousCUstomerButton.setText(_translate("CustomerSearchWidget", "Anonymous (F1)"))
