# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProductSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductSearchWidget(object):
    def setupUi(self, ProductSearchWidget):
        ProductSearchWidget.setObjectName("ProductSearchWidget")
        ProductSearchWidget.resize(828, 532)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProductSearchWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ProductSearchGroupBox = QtWidgets.QGroupBox(ProductSearchWidget)
        self.ProductSearchGroupBox.setObjectName("ProductSearchGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ProductSearchGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SearchLabel = QtWidgets.QLabel(self.ProductSearchGroupBox)
        self.SearchLabel.setObjectName("SearchLabel")
        self.gridLayout_3.addWidget(self.SearchLabel, 0, 0, 1, 1)
        self.SearchField = QtWidgets.QLineEdit(self.ProductSearchGroupBox)
        self.SearchField.setObjectName("SearchField")
        self.gridLayout_3.addWidget(self.SearchField, 0, 1, 1, 3)
        self.ResultsTable = QtWidgets.QTableWidget(self.ProductSearchGroupBox)
        self.ResultsTable.setObjectName("ResultsTable")
        self.ResultsTable.setColumnCount(0)
        self.ResultsTable.setRowCount(0)
        self.gridLayout_3.addWidget(self.ResultsTable, 1, 0, 1, 4)
        self.SelectionLabel = QtWidgets.QLabel(self.ProductSearchGroupBox)
        self.SelectionLabel.setObjectName("SelectionLabel")
        self.gridLayout_3.addWidget(self.SelectionLabel, 2, 0, 1, 2)
        self.SelectionButton = QtWidgets.QPushButton(self.ProductSearchGroupBox)
        self.SelectionButton.setMinimumSize(QtCore.QSize(0, 40))
        self.SelectionButton.setMaximumSize(QtCore.QSize(16777215, 65))
        self.SelectionButton.setObjectName("SelectionButton")
        self.gridLayout_3.addWidget(self.SelectionButton, 2, 2, 1, 1)
        self.InfoButton = QtWidgets.QPushButton(self.ProductSearchGroupBox)
        self.InfoButton.setMinimumSize(QtCore.QSize(0, 40))
        self.InfoButton.setMaximumSize(QtCore.QSize(16777215, 65))
        self.InfoButton.setObjectName("InfoButton")
        self.gridLayout_3.addWidget(self.InfoButton, 2, 3, 1, 1)
        self.horizontalLayout.addWidget(self.ProductSearchGroupBox)

        self.retranslateUi(ProductSearchWidget)
        QtCore.QMetaObject.connectSlotsByName(ProductSearchWidget)

    def retranslateUi(self, ProductSearchWidget):
        _translate = QtCore.QCoreApplication.translate
        ProductSearchWidget.setWindowTitle(_translate("ProductSearchWidget", "Form"))
        self.ProductSearchGroupBox.setTitle(_translate("ProductSearchWidget", "Products"))
        self.SearchLabel.setText(_translate("ProductSearchWidget", "Search:"))
        self.SelectionLabel.setText(_translate("ProductSearchWidget", "SELECTED: [PRODUCT SELECTED]"))
        self.SelectionButton.setText(_translate("ProductSearchWidget", "SELECT"))
        self.InfoButton.setText(_translate("ProductSearchWidget", "INFO"))
